# Generated by Django 3.1 on 2021-08-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='')),
                ('trainer', models.CharField(max_length=500)),
                ('trainer_image', models.ImageField(upload_to='')),
                ('header', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_time', models.CharField(blank=True, max_length=50, null=True)),
                ('ratings', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
