# Generated by Django 3.1 on 2021-08-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepreview',
            name='slug',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
