# Generated by Django 3.1 on 2021-08-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_coursepreview_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepreview',
            name='role',
            field=models.CharField(default='Software Engineer and Developer', max_length=255),
            preserve_default=False,
        ),
    ]
