# Generated by Django 3.1 on 2021-08-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_coursepreview_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('one', models.CharField(blank=True, max_length=255, null=True)),
                ('two', models.CharField(blank=True, max_length=255, null=True)),
                ('three', models.CharField(blank=True, max_length=255, null=True)),
                ('four', models.CharField(blank=True, max_length=255, null=True)),
                ('five', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='coursepreview',
            name='about_course',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='coursepreview',
            name='about_trainer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
