# Generated by Django 3.1 on 2021-08-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210804_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('division_header', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('video_length', models.CharField(blank=True, max_length=10, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('course_slug', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='coursepreview',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
