# Generated by Django 3.1 on 2021-08-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_coursedetails_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepreview',
            name='section_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
