# Generated by Django 3.2.7 on 2021-11-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210831_0924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseDetails',
            new_name='CourseDetail',
        ),
    ]
