# Generated by Django 3.2.7 on 2021-11-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_rename_coursedetails_coursedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepreview',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
