# Generated by Django 3.2.7 on 2021-11-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_coursepreview_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
