# Generated by Django 3.2.7 on 2021-11-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_coursedetail_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepreview',
            name='template_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
