# Generated by Django 3.2.7 on 2021-11-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_coursepreview_template_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepreview',
            name='template_name',
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='template_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
